repos=\
    AaegL3_ensembl \
    AgamP4_ensembl \
    dm3_ensembl \
    dm6_ensembl \
    dvir1.3_ensembl \
    GRCh37_ensembl \
    GRCh38_blueprint \
    GRCh38_ensembl \
    GRCm37_ensembl \
    GRCm38_ensembl \
    GRCz10_ensembl \
    hs37d5_ensembl \
    WBcel235_ensembl \
    Zv9_ensembl 

.PHONY: all

${repos}::
	cd $@; ${MAKE}

all: ${repos}
