repos=\
    dm3_ensembl \
    dm6_ensembl \
    GRCh37_ensembl \
    GRCh38_blueprint \
    GRCh38_ensembl \
    GRCm37_ensembl \
    GRCm38_ensembl \
    Zv9_ensembl

.PHONY: all

${repos}::
	cd $@; ${MAKE}

all: ${repos}
